# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogo < Formula
  desc "Streaming LLM CLI with multi-provider support"
  homepage "https://github.com/sirsjg/gogo"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirsjg/gogo/releases/download/v0.2.0/gogo_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "275519a5316d9fb72df7744ee85568ced5abf8b29e32ed5b48c587b30820c75a"

      def install
        bin.install "gogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirsjg/gogo/releases/download/v0.2.0/gogo_0.2.0_Darwin_arm64.tar.gz"
      sha256 "12b42848b32d8174d186af5de661f4d8c7c22fcb8b887a7aa106bfc369674b5e"

      def install
        bin.install "gogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/gogo/releases/download/v0.2.0/gogo_0.2.0_Linux_x86_64.tar.gz"
      sha256 "d54bc148a702d51c04228c70297618df974e402eceda206b35ae3bb0fab36004"
      def install
        bin.install "gogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/gogo/releases/download/v0.2.0/gogo_0.2.0_Linux_arm64.tar.gz"
      sha256 "8cb4c9a79891fe58075e3c3b88848e41f51a10c286af3be4e7f008dd4e7b0aac"
      def install
        bin.install "gogo"
      end
    end
  end

  test do
    system "#{bin}/gogo", "-v"
  end
end
