# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gogo < Formula
  desc "Streaming LLM CLI with multi-provider support"
  homepage "https://github.com/sirsjg/gogo"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sirsjg/gogo/releases/download/v0.1.0/gogo_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "7396bdaf5882a4df00eeb7010cae6fab423ccb0b9adb332ffdc512e0c77d4eed"

      def install
        bin.install "gogo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sirsjg/gogo/releases/download/v0.1.0/gogo_0.1.0_Darwin_arm64.tar.gz"
      sha256 "072f26a574e6f848fd9ef27bb0d5e5f89b6ef2f78bb2c8605b74e07f84b9cad1"

      def install
        bin.install "gogo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/gogo/releases/download/v0.1.0/gogo_0.1.0_Linux_x86_64.tar.gz"
      sha256 "422cf79917bd00cf12fb54655ded807aca78d06eeb1b4ffd78b1df53d214e305"
      def install
        bin.install "gogo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirsjg/gogo/releases/download/v0.1.0/gogo_0.1.0_Linux_arm64.tar.gz"
      sha256 "6cfa157978b45ac4d5d6b8f0034ad249de5825694d5154cc09e063027aaacbe7"
      def install
        bin.install "gogo"
      end
    end
  end

  test do
    system "#{bin}/gogo", "-v"
  end
end
